apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: campushub

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - mqtt.yaml
  - kafka.yaml
  - backend.yaml
  - frontend.yaml
  - prometheus.yaml
  - grafana.yaml
  - node-exporter.yaml
  - mqtt-subscriber.yaml
  - kafka-consumer.yaml
