apiVersion: v1
kind: Secret
metadata:
  name: campushub-postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: campushub
  POSTGRES_PASSWORD: campushub_dev
  POSTGRES_DB: campushub
  DATABASE_URL: postgresql+psycopg://campushub:campushub_dev@campushub-postgres:5432/campushub